#!/usr/bin/env bash
# vim:fileencoding=utf-8:foldmethod=marker
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

## functions and constants {{{
# check wether or not macOS is in dark mode
if [[ $(defaults read -g AppleInterfaceStyle) != 'Dark' ]]; then
  THEME="light"
else
  THEME="dark"
fi

# catppuccin Mocha colours {{{
if [[ $THEME == 'dark' ]]; then
  ROSEWATER="f5e0dc"
  FLAMINGO="f2cdcd"
  PINK="f5c2e7"
  MAUVE="cba6f7"
  RED="0xfff38ba8"
  MAROON="eba0ac"
  PEACH="fab387"
  YELLOW="f9e2af"
  GREEN="a6e3a1"
  TEAL="94e2d5"
  SKY="89dceb"
  SAPPHIRE="74c7ec"
  BLUE="89b4fa"
  LAVENDER="b4befe"
  TEXT="cdd6f4"
  SUBTEXT1="bac2de"
  SUBTEXT0="a6adc8"
  OVERLAY2="9399b2"
  OVERLAY1="7f849c"
  OVERLAY0="6c7086"
  SURFACE2="585b70"
  SURFACE1="45475a"
  SURFACE0="313244"
  BASE="1e1e2e"
  MANTLE="181825"
  CRUST="11111b"
else
  ROSEWATER="dc8a78"
  FLAMINGO="dd7878"
  PINK="ea76cb"
  MAUVE="8839ef"
  RED="d20f39"
  MAROON="e64553"
  PEACH="fe640b"
  YELLOW="df8e1d"
  GREEN="40a02b"
  TEAL="179299"
  SKY="04a5e5"
  SAPPHIRE="209fb5"
  BLUE="1e66f5"
  LAVENDER="7287fd"
  TEXT="4c4f69"
  SUBTEXT1="5c5f77"
  SUBTEXT0="6c6f85"
  OVERLAY2="7c7f93"
  OVERLAY1="8c8fa1"
  OVERLAY0="9ca0b0"
  SURFACE2="acb0be"
  SURFACE1="bcc0cc"
  SURFACE0="ccd0da"
  CRUST="dce0e8"
  MANTLE="e6e9ef"
  BASE="eff1f5"
fi

function color() {
  alpha=${2:-255}
  color="$1"

  case $1 in
    rosewater) color=$ROSEWATER ;;
    flamingo) color=$FLAMINGO ;;
    pink) color=$PINK ;;
    mauve) color=$MAUVE ;;
    red) color=$RED ;;
    maroon) color=$MAROON ;;
    peach) color=$PEACH ;;
    yellow) color=$YELLOW ;;
    green) color=$GREEN ;;
    teal) color=$TEAL ;;
    sky) color=$SKY ;;
    sapphire) color=$SAPPHIRE ;;
    blue) color=$BLUE ;;
    lavender) color=$LAVENDER ;;
    text) color=$TEXT ;;
    subtext1) color=$SUBTEXT1 ;;
    subtext0) color=$SUBTEXT0 ;;
    overlay2) color=$OVERLAY2 ;;
    overlay1) color=$OVERLAY1 ;;
    overlay0) color=$OVERLAY0 ;;
    surface2) color=$SURFACE2 ;;
    surface1) color=$SURFACE1 ;;
    surface0) color=$SURFACE0 ;;
    crust) color=$CRUST ;;
    mantle) color=$MANTLE ;;
    base) color=$BASE ;;
    *) color=$BASE ;;
  esac
  printf -v alpha "%02x" "$alpha"
  echo "0x${alpha}${color}"
}
# }}}
## }}}

## bar appearance {{{
sketchybar --bar \
  height=32 \
  blur_radius=10 \
  position=top \
  padding_left=0 \
  padding_right=4 \
  color=$(color crust 200)

sketchybar -m --add event theme_changed AppleInterfaceThemeChangedNotification
sketchybar \
  --add item dummy left \
  --set dummy \
    icon.drawing=off \
    label.drawing=off \
    script="$PLUGIN_DIR/kickstart.sh" \
  --subscribe dummy theme_changed

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default \
  updates=when_shown \
  drawing=on \
  icon.font="Symbols Nerd Font:2048-em:18.0" \
  icon.color=$(color pink) \
  label.font="Victor Mono:Bold:16.0" \
  label.color=$(color text) \
  label.padding_left=1 \
  label.padding_right=1 \
  icon.padding_left=8 \
  icon.padding_right=8
# }}}

## left side of the bar {{{

# spaces for yabai wm
SPACE_ICONS=(
" "
" "
" "
" "
" "
" "
" "
" "
" "
" "
)
for i in "${!SPACE_ICONS[@]}"
do
  if [[ $i == 0 ]]; then
    lbgp=0
  else
    lbgp=1
  fi

  sketchybar \
    --add space "space.$i" left \
    --set "space.$i" associated_space=$(($i+1)) \
      icon="${SPACE_ICONS[i]}" \
      icon.highlight_color=$(color pink) \
      icon.padding_left=8 \
      icon.padding_right=8 \
      background.padding_left="$lbgp" \
      background.padding_right=1 \
      background.color=$(color overlay2) \
      background.height=32 \
      label.drawing=off \
      script="$PLUGIN_DIR/space.sh" \
      click_script="yabai -m space --focus $(($i+1))"
done

# window title
sketchybar \
  --add item window_title left \
  --set window_title \
    icon.color=$(color text) \
    label.color=$(color text) \
    background.padding_left=8 \
    script="$PLUGIN_DIR/window_title.sh" \
  --subscribe window_title front_app_switched

## }}}

## middle of the bar {{{

# Apple Music Status
sketchybar -m --add event song_update com.apple.Music.playerInfo
sketchybar \
--add item music center \
--set music \
  icon.color=$(color subtext1) \
  label.color=$(color subtext1) \
  label.font="Victor Mono:Bold Italic:16.0" \
  script="$PLUGIN_DIR/music.sh" \
--subscribe music song_update
# }}}

## right side of the bar {{{

# this starts at the rightmost item
# items should be self explanatory by their name, and are separated by a blank line
sketchybar \
\
  --add item clock right \
  --set clock \
    script="$PLUGIN_DIR/clock.sh" \
    update_freq=10 \
    icon.color=$(color mauve) \
    label.color=$(color mauve) \
\
  --add item date right \
  --set date \
    script="$PLUGIN_DIR/ddate.sh" \
    icon.color=$(color blue) \
    label.color=$(color blue) \
\
  --add item mullvad right \
  --set mullvad \
    script="$PLUGIN_DIR/mullvad.sh" \
    update_freq=10 \
    icon.color=$(color green) \
    label.color=$(color green) \
\
  --add item battery right \
  --set battery \
    update_freq=30 \
    script="$PLUGIN_DIR/battery.sh" \
    icon.color=$(color yellow) \
    label.color=$(color yellow) \
  --subscribe battery system_woke \
\
  --add item sound right \
  --set sound \
    script="$PLUGIN_DIR/sound.sh" \
    update_freq=5 \
    icon.color=$(color peach) \
    label.color=$(color peach) \
\
  --add item mail right \
  --set mail \
    script="$PLUGIN_DIR/mailIndicator.sh" \
    update_freq=10 \
    icon.color=$(color red) \
    label.color=$(color red) \
\
  --add item tasks right \
  --set tasks \
    script="$PLUGIN_DIR/tasks.sh" \
    update_freq=10 \
    icon.color=$(color red) \
    label.color=$(color red)

##### fin #####
sketchybar --update
